server:
  port: 0
 # servlet:
 #   contextPath: /SAMPLE-APPLICATION
 # use-forward-headers: false
 

logging:
  file: log.log
  level:
    org:
      springframework: #DEBUG

spring:
  profiles:
    active: test
  datasource:
    name: test
    url: jdbc:hsqldb:mem:test2://localhost/sampleApp
    username:
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: none
      
security:
  basic:
    enabled: false
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0DsrJige51wEhIDatvnq
          zGlrb+HGZmUCB7UxxoP7m+humK6paRilkpKKXoJeiwrYz2Cx9dLG1Q0IxtOlxPU4
          RsCjFw3N8hrmuw+R8Fn6d0wAXUFR3EjoyiNaGK++2RaTEsbzK1A1/ea6DKH1UuFB
          +NL1BQacKtQH3mwe/7ot9uW1axKwb28cqxHBYwxIdK8gQumCrLdwd9d+ZFn6j+7z
          9VszKolOnmkeo1bOFNGBJ2Vf4b6XQc/uukpSDmV2l2pLMQ/DVLWvU/cl9Wd7S8CQ
          pIQiKzmnKlbvM18EVDZwb0vcXZenT5yGHZ3GHXEJDzChnRbQtQOjvUvKzPnoBzGx
          7wIDAQAB
          -----END PUBLIC KEY-----
#    client:
#      client-id: LITSystem
#      client-secret: LITSystem
#      access-token-uri: http://localhost:5000/uaa/oauth/token
#      grant-type: client_credentials
#      scope: system
      
eureka:
  instance:
    hostname: localhost
    port: 8761
    healthCheckUrlPath: ${management.contextPath}/health
    metadata-map:
      management.context-path: "${management.contextPath}"
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka
      
management:
  contextPath: /mgmt
  security:
    enabled: false
    
endpoints:
  enabled: false
  health.enabled: true
  info.enabled: true
  logfile.enabled: true
  loggers.enabled: true
  metrics.enabled: true
  trace.enabled: true


---
  

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/LIT?characterEncoding=UTF-8
    username: root
    password: $LIT2016$
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
    show_sql: true
    hibernate:
      ddl-auto: update
      
security:
  oauth2:
    resource:
      filter-order: 3
      userInfoUri: http://localhost:8080/uaa/user #uaa-service/uaa/user
#    client:
#      clientId: LITSystem
#      clientSecret: LITSecret
#      accessTokenUri: http://localhost:8080/uaa/oauth/token
#      grant-type: client_credentials
#      scope: system

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka
   